import { BASE_FIELDS, COMPANY_FIELDS, makeCategory } from "./helpers";
import { BRANCH_FIELDS, COMPANY_EXTRA_FIELDS } from "./fieldPresets";
import type { MasterCategoryConfig } from "../types";

const companyScoped = { companyScoped: true, formFields: COMPANY_FIELDS };

export const MASTER_CATEGORIES: MasterCategoryConfig[] = [
  makeCategory(
    "employee",
    "Employee Masters",
    [
      "Gender",
      "Salutation",
      "MaritalStatus",
      "Religion",
      "Caste",
      "CasteCategory",
      "MotherTongue",
      "Nationality",
      "BloodGroup",
      "EmployeeType",
      "EmployeeStatus",
      "EmployeeCategory",
      "Designation",
      "Department",
      "Grade",
      "SkillCategory",
      "ShiftGroup",
      "ReportingManagerMapping",
      "OfficeLocation",
      "HeadquarterLocation",
      "LocationType",
      "ProbationPolicy",
      "SeparationMode",
      "PositionChangeReason",
      "DocumentType",
      "DocumentSide",
      "Qualification",
      "EducationLevel",
      "EducationStatus",
      "Board",
      "Specialization",
      "EducationSpecialization",
      "StudyMode",
      "WorkExperienceRange",
      "RelevantExperienceRange",
      "LanguageProficiency",
      "ProficiencyLevel",
      "Language",
      "CertificationBody",
      "CertificationMaster",
      "EmployeeTag",
      "EmployeeNumberSeries",
      "SourceOfHire",
      "SourceOfHireType",
      "TransportType",
      "PayrollStatus",
      "PayrollMode",
      "PayrollGroup",
      "PolicyType",
      "InsuranceType",
      "CoverType",
      "PremiumFrequency",
      "InsuranceCompany",
      "NomineePurpose",
      "Relation",
      "Occupation",
      "Profession",
      "CommunicationChannel",
      "CommunicationTask",
      "EmployeeFilter",
      "ContractStatus",
      "VerificationStatus",
      "ResidentialStatus",
    ],
    {
      Gender: { constant: true },
      MaritalStatus: { constant: true },
      BloodGroup: { constant: true },
      Designation: companyScoped,
      Department: {
        companyScoped: true,
        parentFieldKey: "parent_department",
        formFields: [
          ...COMPANY_FIELDS,
          { key: "parent_department", label: "Parent Department", type: "select", relationMaster: "Department" },
        ],
      },
      Grade: companyScoped,
      OfficeLocation: { label: "Work Location", ...companyScoped },
      HeadquarterLocation: companyScoped,
      Qualification: { label: "Education Qualification" },
      WorkExperienceRange: { label: "Experience Level" },
      CertificationMaster: { label: "Certification Masters" },
      EmployeeStatus: { label: "Employment Status" },
      SeparationMode: { label: "Exit Reason" },
    },
  ),
  makeCategory(
    "attendance",
    "Attendance Masters",
    [
      "Shift",
      "ShiftType",
      "ShiftRotation",
      "AttendanceStatus",
      "AttendanceScheme",
      "RegularizationReason",
      "PunchPolicy",
      "LateMarkRule",
      "EarlyExitRule",
      "OvertimePolicy",
      "BreakRule",
      "HolidayGroup",
      "WorkWeekPolicy",
      "BiometricDeviceMapping",
      "AttendancePolicy",
      "GeoFenceMaster",
      "WorkMode",
      "RosterTemplate",
      "CompOffPolicy",
      "AttendancePenaltyRule",
      "SwipeConfiguration",
    ],
    {
      Shift: { label: "Shift Master", ...companyScoped },
      ShiftType: companyScoped,
      RegularizationReason: { label: "Attendance Regularization Types" },
      OvertimePolicy: { label: "Overtime Rules" },
      CompOffPolicy: { label: "Comp Off Rules" },
      WorkWeekPolicy: { label: "Weekend Policy", ...companyScoped },
      HolidayGroup: companyScoped,
    },
  ),
  makeCategory(
    "leave",
    "Leave Masters",
    [
      "LeaveType",
      "LeavePolicy",
      "LeaveAccrualRule",
      "LeaveEncashmentRule",
      "LeaveCarryForwardRule",
      "LeaveApprovalMatrix",
      "LeaveEscalationMatrix",
      "HolidayCalendar",
      "Holiday",
      "RestrictedHoliday",
      "LeaveBalanceSetting",
      "SandwichLeaveRule",
      "ProbationLeaveRule",
      "MaternityPaternityRule",
      "CompensatoryLeaveRule",
      "LeaveDocumentRule",
      "LeaveCancellationRule",
      "LeaveReasonMaster",
      "LeaveBlackoutDate",
    ],
    {
      LeaveApprovalMatrix: { label: "Leave Approval Workflow" },
      HolidayCalendar: companyScoped,
      Holiday: companyScoped,
    },
  ),
  makeCategory(
    "payroll",
    "Payroll Masters",
    [
      "PayComponentGroup",
      "PayComponent",
      "Band",
      "TaxRegime",
      "ReimbursementType",
      "PfScheme",
      "EsiScheme",
      "BonusRule",
      "DeductionType",
      "LoanType",
      "PayrollCycle",
      "SalaryStructure",
      "SalaryStructureComponent",
      "Bank",
      "PayrollApprovalWorkflow",
      "TdsSection",
      "ArrearType",
      "StatutoryComponent",
      "PtStateSlab",
      "LwfSlab",
      "LabourRegisterType",
      "BankStatus",
      "AccountType",
      "PaymentType",
    ],
    {
      PayComponentGroup: {
        label: "Salary Components",
        formFields: [...BASE_FIELDS, { key: "is_earning", label: "Is Earning", type: "boolean" }],
      },
      PayComponent: {
        formFields: [...BASE_FIELDS, { key: "pay_component_group", label: "Component Group", type: "select", relationMaster: "PayComponentGroup" }],
      },
      Band: { label: "Pay Grades" },
      PfScheme: { label: "PF Settings" },
      EsiScheme: { label: "ESI Settings" },
      SalaryStructure: { label: "Salary Structures" },
      Bank: { label: "Bank Master" },
    },
  ),
  makeCategory(
    "organization",
    "Organization Masters",
    [
      "Company",
      "Branch",
      "BusinessUnit",
      "DepartmentDivision",
      "CostCenter",
      "ProfitCenter",
      "Region",
      "Zone",
      "Country",
      "State",
      "City",
      "ProductionCell",
      "Floor",
      "SeatingZone",
      "Extension",
      "Batch",
      "Cab",
    ],
    {
      Company: { formFields: COMPANY_EXTRA_FIELDS, listColumns: ["code", "label", "pan", "gstin"] },
      Branch: { companyScoped: true, formFields: BRANCH_FIELDS },
      BusinessUnit: companyScoped,
      DepartmentDivision: { label: "Division", ...companyScoped },
      CostCenter: companyScoped,
      ProfitCenter: companyScoped,
      State: {
        parentFieldKey: "country",
        formFields: [...BASE_FIELDS, { key: "country", label: "Country", type: "select", relationMaster: "Country", required: true }],
      },
      City: {
        parentFieldKey: "state",
        formFields: [...BASE_FIELDS, { key: "state", label: "State", type: "select", relationMaster: "State", required: true }],
      },
      Floor: { label: "Floor / Wing" },
    },
  ),
  makeCategory(
    "recruitment",
    "Recruitment Masters",
    [
      "JobFunction",
      "InterviewRound",
      "CandidateSource",
      "OfferStatus",
      "PipelineStage",
      "OfferTemplate",
      "InterviewPanel",
      "RejectionReason",
      "SkillAssessmentType",
      "JobLevel",
    ],
    {
      JobFunction: { label: "Job Role" },
      InterviewRound: { label: "Interview Type" },
      CandidateSource: { label: "Hiring Source" },
      OfferStatus: { label: "Candidate Status" },
      PipelineStage: { label: "Recruitment Stage" },
    },
  ),
  makeCategory(
    "performance",
    "Performance Masters",
    [
      "KpiLibrary",
      "GoalCategory",
      "AppraisalCycle",
      "CompetencyGroup",
      "Competency",
      "RatingScale",
      "FeedbackTemplate",
      "KraLibrary",
      "PerformanceBand",
    ],
    {
      KpiLibrary: { label: "KPI Templates" },
      AppraisalCycle: { label: "Review Cycles" },
      CompetencyGroup: { label: "Competency Types" },
    },
  ),
  makeCategory(
    "training-asset",
    "Training & Asset Masters",
    [
      "TrainingCategory",
      "TrainingMode",
      "TrainerType",
      "Course",
      "AssetCategory",
      "AssetCondition",
      "AssetType",
      "AssetStatus",
      "AssetAllocationType",
      "Vendor",
    ],
    {
      AssetCondition: { label: "Asset Status" },
      Vendor: { label: "Vendor Master" },
    },
  ),
  makeCategory(
    "workflow-security",
    "Workflow & Security Masters",
    [
      "WorkflowType",
      "SystemRole",
      "DefaultRole",
      "Permission",
      "NotificationTemplate",
      "EscalationType",
      "AuditEventType",
      "PasswordPolicy",
      "SessionPolicy",
      "NotificationChannel",
      "NotificationTrigger",
      "ApprovalAction",
      "MenuItem",
      "DataScopeType",
      "BulletinCategory",
      "PolicyCategory",
      "FormCategory",
      "ImportType",
      "LetterApprovalType",
      "ClearanceItemType",
      "CounterParty",
      "AuthorizedSignatory",
    ],
    {
      WorkflowType: { label: "Approval Workflow" },
      SystemRole: { label: "Role Master" },
      Permission: { label: "Permission Groups" },
      EscalationType: { label: "Escalation Rules" },
      AuditEventType: { label: "Audit Categories" },
      PasswordPolicy: { label: "Access Policies" },
    },
  ),
];
